kind: ConfigMap
apiVersion: v1
metadata:
  name: ocs-fio-config
  namespace: ocs-tests
data:
  fioconfig: >
    [global]

    name=fio-test

    directory=/data/ #This is the directory where files are written

    ioengine=libaio #Async threads, jobs turned over to asynch threads and core
    moves on

    direct=1 #Use directio, if you use libaio and NFS this must be set to 1
    enabling directio

    numjobs=1 #To match how many users on the system

    nrfiles=1 #Num files per job

    runtime=120 #If time_based is set, run for this amount of time

    group_reporting #This is used to aggregate the job results, otherwise you
    have lots of data to parse

    time_based #This setting says run the jobs until this much time has elapsed

    stonewall

    bs=64K

    rw=rw #choose rw if sequential io, choose randrw for random io

    rwmixread=100 #<-- Modify to get different i/o distributions

    iodepth=15 #<-- Modify this to get the i/o they want (latency * target op
    count)

    size=4G #Aggregate file size per job (if nrfiles = 4, files=2.5GiB)

    ramp_time=20 #Warm up

    [rw]

    [randrw]
