
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: testdisk-ocp
spec:
  #storageClassName: ssd
  # storageClassName: gp2
  # storageClassName: local-storage
  # storageClassName: ibmc-block-bronze
  # storageClassName: ibmc-block-silver
  # storageClassName: ibmc-block-gold
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdisk-ocp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdisk-ocp
  template:
    metadata:
      labels:
        app: testdisk-ocp
    spec:
      containers:
      - name: testdisk-ocp
        image: "docker.io/sourcesense/testdisk-ocp:latest"
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: ocs-fio-config
          mountPath: /tmp/
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: testdisk-ocp
      - name: ocs-fio-config
        configMap:
          name: ocs-fio-config
          defaultMode: 420
